### ISSUE TITLE
Trying to edit the fork I had created

### ISSUE THREAD

**Issue by jsromero1721** [hackclub/winter#296]
Hey I was trying to edit the fork I have made the other day but it doesn't seem I can edit or make a new one. I have barely started my fork when my computer had restarted and wasn't able to save or do anything to it. What can I do here?

**Comment by Arpan-206** [comment]
Want to hop on Slack so I can try to help.

**Comment by jsromero1721** [comment]
> Want to hop on Slack, so I can try to help?

Could you send me the link please and thank you

**Comment by Arpan-206** [comment]
https://hackclub.zoom.us/j/85943655601?pwd=ZG1YOFZ4TmhhV0pGQ2ZqWVZsYnBYQT09

Just ping me before joining, my slack username: Arpan.

**Comment by jsromero1721** [comment]
I’ll do it once I’m home because I’m in school at the moment

**Comment by Arpan-206** [comment]
Sure, just message me

**Comment by reesericci** [comment]
fyi - don't post zoom links publicly on github

**Comment by Arpan-206** [comment]
Yeah, realised it later and deactivated it

**Comment by whatwareweb** [comment]
You can just edit your original repo - the PR will automatically be updated.

**Comment by exu3** [comment]
Closing this as the deadline to submit projects has passed. Feel free to reach out in #hardware-party on Slack with any questions!
